# Generated by Django 2.1.5 on 2019-01-10 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('instruction', models.TextField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('show_result', models.IntegerField(choices=[('', 'Choose...'), (1, 'Yes'), (0, 'No')])),
                ('show_instruction', models.IntegerField(choices=[('', 'Choose...'), (1, 'Yes'), (0, 'No')])),
                ('is_active', models.IntegerField(choices=[('', 'Choose...'), (1, 'Yes'), (0, 'No')])),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Category'),
        ),
    ]
